#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/_env.sh"

version="${PHP_VERSION}"

docker compose run --rm "php${version}" vendor/bin/phpstan analyse --memory-limit=1G "$@"
